#!/usr/bin/env python3
"""Bit-exact golden model of the dual-core Jacobi CPU (Q15.16 fixed point).

Reproduces exactly what the RTL computes, instruction by instruction:
  mul : (A * B) >>> 16          64-bit signed product, arithmetic shift, keep low 32 bits
  div : (A <<< 16) / B          64-bit signed dividend, truncation toward zero (SV '/'), keep low 32 bits
  add/sub : 32-bit two's complement wrap
Each row x_i = (b_i - sum_{j!=i} a_ij * x_j) / a_ii is evaluated with one mul per
off-diagonal term (rounded individually), matching the instruction sequence in
rtl/instruction_memory_{0,1}.sv.

--recip models variants/recip.patch: the diagonal slot holds 1/a_ii (Q15.16, rounded once)
and the row update multiplies by it instead of dividing by a_ii.

Usage:
  python3 model/jacobi_golden.py                     # print convergence table
  python3 model/jacobi_golden.py --svh build/golden_expected.svh
  python3 model/jacobi_golden.py --recip [--svh ...]
"""

import argparse
from fractions import Fraction

Q = 16
ONE = 1 << Q

# Testbench system from the report (A x = b, x0 = 0, 50 iterations)
A = [[10, 1, 2, 1],
     [2, 12, 1, 2],
     [1, 1, 15, 1],
     [1, 2, 1, 11]]
B = [2, 2, 2, 2]
ITERS = 50


def s32(v):
    """Wrap to signed 32-bit."""
    v &= 0xFFFFFFFF
    return v - (1 << 32) if v & 0x80000000 else v


def q_mul(a, b):
    return s32((a * b) >> Q)  # Python >> on negatives is arithmetic (floor) like SV >>>


def q_div(a, b):
    if b == 0:
        return 0  # alu.sv: divide-by-zero returns 0
    n = a << Q
    q = abs(n) // abs(b)
    return s32(q if (n >= 0) == (b > 0) else -q)  # truncate toward zero


def to_q(v):
    return s32(int(v * ONE))


def inv_diag(a):
    """1/a_ii in Q15.16, rounded to nearest (what the recip variant stores in the diagonal slot)."""
    return [int(ONE / a[i][i] + 0.5) for i in range(len(a))]


def jacobi_fixed(a, b, iters, recip=False):
    """Return list of x vectors (Q15.16 ints); index k = state after k iterations."""
    aq = [[to_q(v) for v in row] for row in a]
    bq = [to_q(v) for v in b]
    inv = inv_diag(a)
    n = len(b)
    x = [0] * n
    hist = [x[:]]
    for _ in range(iters):
        new = []
        for i in range(n):
            acc = 0
            for j in range(n):
                if j != i:
                    acc = s32(acc + q_mul(aq[i][j], x[j]))
            num = s32(bq[i] - acc)
            new.append(q_mul(num, inv[i]) if recip else q_div(num, aq[i][i]))
        x = new
        hist.append(x[:])
    return hist


def jacobi_float(a, b, iters):
    n = len(b)
    x = [0.0] * n
    hist = [x[:]]
    for _ in range(iters):
        x = [(b[i] - sum(a[i][j] * x[j] for j in range(n) if j != i)) / a[i][i] for i in range(n)]
        hist.append(x[:])
    return hist


def exact_solution(a, b):
    """Gaussian elimination in rationals."""
    n = len(b)
    m = [[Fraction(v) for v in row] + [Fraction(b[i])] for i, row in enumerate(a)]
    for c in range(n):
        p = next(r for r in range(c, n) if m[r][c] != 0)
        m[c], m[p] = m[p], m[c]
        for r in range(n):
            if r != c and m[r][c] != 0:
                f = m[r][c] / m[c][c]
                m[r] = [x - f * y for x, y in zip(m[r], m[c])]
    return [m[i][n] / m[i][i] for i in range(n)]


def write_svh(path, hist, recip):
    iters = len(hist) - 1
    inv = inv_diag(A)
    lines = [
        "// Generated by model/jacobi_golden.py -- do not edit.",
        "// golden[k][i] : x_(i+1) after k Jacobi iterations, Q15.16 raw value.",
        f"localparam int GOLDEN_ITERS = {iters};",
        f"localparam int GOLDEN_RECIP = {int(recip)};",
        "// 1/a_ii in Q15.16 (stored in the diagonal slot by the recip variant)",
    ] + [f"localparam int INV_A{i + 1}{i + 1} = {v};" for i, v in enumerate(inv)] + [
        f"int golden [0:{iters}][0:3];",
        "initial begin",
    ]
    for k, x in enumerate(hist):
        lines.append("  " + " ".join(f"golden[{k}][{i}] = {v};" for i, v in enumerate(x)))
    lines.append("end")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--iters", type=int, default=ITERS)
    ap.add_argument("--svh", help="write SystemVerilog include with expected values")
    ap.add_argument("--recip", action="store_true", help="model the reciprocal-multiply variant")
    args = ap.parse_args()

    fx = jacobi_fixed(A, B, args.iters, recip=args.recip)
    fl = jacobi_float(A, B, args.iters)
    ex = [float(v) for v in exact_solution(A, B)]

    if args.svh:
        write_svh(args.svh, fx, args.recip)
        print(f"wrote {args.svh} ({args.iters} iterations)")
        return

    print("Q15.16 golden model  (raw / decimal)" + ("  [recip: x_i = num * 1/a_ii, 1/a_ii = %s]" % inv_diag(A) if args.recip else ""))
    print(f"{'k':>3} | " + " | ".join(f"{'x' + str(i + 1):>18}" for i in range(4)))
    for k in sorted({1, 2, 5, 10, 20, 30, 40, args.iters}):
        if k <= args.iters:
            print(f"{k:>3} | " + " | ".join(f"{v:>7} {v / ONE:10.8f}" for v in fx[k]))

    last = fx[args.iters]
    print("\nfinal vs float Jacobi vs exact solution")
    for i in range(4):
        q = last[i] / ONE
        print(f"  x{i + 1}: fixed {q:.8f}  float {fl[args.iters][i]:.10f}  exact {ex[i]:.10f}"
              f"  |fixed-exact| {abs(q - ex[i]):.2e}  ({abs(q - ex[i]) * ONE:.1f} LSB)")

    for k in range(1, args.iters + 1):
        if fx[k] == fx[k - 1]:
            print(f"\nfixed-point iterate stops changing at k = {k - 1}")
            break


if __name__ == "__main__":
    main()
